spring:
  application:
    name: e-health
server:
  port: 8080
eureka:
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://192.168.10.8:8761/eureka